### ISSUE TITLE
Missing data types in nested struct

### ISSUE THREAD

**Issue by cixtor** [mholt/json-to-go#53] opened 2019-03-06 05:55 UTC
Take the JSON object below and try to generate a Go struct.

You’ll notice that both “user_agent” and “referer” will end up lacking the “string” type.

```
{
  "project": "90368",
  "logger": "javascript",
  "platform": "javascript",
  "request": {
    "user_agent": "Foobar",
    "referer": "https://cixtor.com/"
  },
  "release": "v3-1633-gbb54e4ad",
  "event_id": "b0cfac40a3374cc686b1"
}
```

![missingtype](https://user-images.githubusercontent.com/1933999/53859006-2419f700-3f91-11e9-80c9-d0483db43606.gif)

**Comment by mahdi-hosseini** [comment] 2019-03-06 06:12
Thanks for reporting. It appears to be a regression caused by https://github.com/mholt/json-to-go/pull/47. I will work on a fix.

**Comment by mahdi-hosseini** [comment] 2019-03-06 06:27
https://github.com/mholt/json-to-go/pull/52 should address it when it gets merged.

**Closed** 2019-03-07 04:49 UTC

**Comment by cixtor** [comment] 2019-03-07 19:59
@mahdi-hosseini — @mholt : are you two completely sure this bug has been fixed?

I just tested this JSON in the live version of the project and it still fails to add some types:

```
{
  "id": 123,
  "username": "john",
  "licenses": [
    {
      "id": 123,
      "spots": 3,
      "volume": false,
      "team": null,
      "available": true,
      "bundle_identifier": "com.example.Foo"
    }
  ],
  "volume_licenses": [],
  "team_subscription": false
}
```

Notice how all the fields inside Licenses are missing the type:

```
type AutoGenerated struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
	Licenses []struct {
		ID               `json:"id"`
		Spots            `json:"spots"`
		Volume           `json:"volume"`
		Team             `json:"team"`
		Available        `json:"available"`
		BundleIdentifier `json:"bundle_identifier"`
	} `json:"licenses"`
	VolumeLicenses   []interface{} `json:"volume_licenses"`
	TeamSubscription bool          `json:"team_subscription"`
}
```

**Comment by mholt** [comment] 2019-03-07 20:01
Yes, I'm sure. I get:

```go
type AutoGenerated struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
	Licenses []struct {
		ID               int         `json:"id"`
		Spots            int         `json:"spots"`
		Volume           bool        `json:"volume"`
		Team             interface{} `json:"team"`
		Available        bool        `json:"available"`
		BundleIdentifier string      `json:"bundle_identifier"`
	} `json:"licenses"`
	VolumeLicenses   []interface{} `json:"volume_licenses"`
	TeamSubscription bool          `json:"team_subscription"`
}
```

Make sure your cache is totally cleared.

**Comment by cixtor** [comment] 2019-03-07 20:02
Oh! You are right 😲 it was the browser cache. Thank you very much 👍
