### ISSUE TITLE
can json-to-go convert  without nest struct

### ISSUE THREAD

**Issue by yale8848** [mholt/json-to-go#37] opened 2018-03-07 10:29 UTC
```
{
"a":{
"b":{
"c":"d"
}
}
}
```
json-to-go will convert json to under:

```
type AutoGenerated struct {
	A struct {
		B struct {
			C string `json:"c"`
		} `json:"b"`
	} `json:"a"`
}
```
can json-to-go convert like this without nest struct?

```
type AutoGeneratedAB struct {
	C string `json:"c"`
}
type AutoGeneratedA struct {
	B AutoGeneratedAB `json:"b"`
}
type AutoGenerated struct {
	A  AutoGeneratedA `json:"a"`
}
```

**Comment by mholt** [comment] 2018-03-09 16:08
Duplicate of #35

**Closed by mholt** 2018-03-09 16:08 UTC
