### ISSUE TITLE
Option to generate non-anonymous structs as output

### ISSUE THREAD

**Issue by itzurabhi** [mholt/json-to-go#35] opened 2017-11-29 07:42 UTC
I have found this application extremely useful. Thank you for your time and effort!

However, to enable the re-use of the nested structures ( not just for parsing ) , It would be great to have an option to generate named structs.
Instead of this 
```
type ConfigurationData struct {
	ApplicationDisplay struct {
		Title          string `json:"title"`
		Subtitle       string `json:"subtitle"`
		WelcomeMessage string `json:"welcomeMessage"`
	} `json:"applicationDisplay"`
}
```
it would generate 
```
type ApplicationDisplay struct {
    Title          string `json:"title"`
    Subtitle       string `json:"subtitle"`
    WelcomeMessage string `json:"welcomeMessage"`
}

type ConfigurationData struct {
    ApplicationDisplay ApplicationDisplay `json:"applicationDisplay"`
}
```

**Comment by bobbytables** [comment] 2018-01-17 15:25
Yeah I'd love this too, @mholt any idea where a good place to start on this would be? Maybe I can take a crack at it.

**Comment by mholt** [comment] 2018-01-17 17:23
Maybe if the third argument to the `jsonToGo` function was optional and, if true, would split out the types. I haven't thought about how it'd be implemented. Maybe an object to map the type names to their definitions as you recursively parse the structure.

**Comment by gabrielruiu** [comment] 2018-08-29 16:57
I would like give this feature a try. But before that, I'm interested in understanding how active the developer is before attempting to contribute. I've noticed there's a PR (https://github.com/mholt/json-to-go/pull/25) which has gone untouched for some time. I would like to know, if I actually get this done that it will be merged.

Additionally, great job on the library!

**Comment by mholt** [comment] 2018-08-29 17:10
@gabrielruiu 

> I would like give this feature a try. But before that, I'm interested in understanding how active the developer is before attempting to contribute. I've noticed there's a PR (#25) which has gone untouched for some time. I would like to know, if I actually get this done that it will be merged.

I'm here -- that PR is inactive because the author didn't respond to my review.

**Comment by mholt** [comment] 2018-12-23 01:57
For the record, this is still up for grabs if anyone wants to tackle it.

**Comment by mholt** [comment] 2019-03-04 02:53
Done in #47

**Closed by mholt** 2019-03-04 02:53 UTC

**Comment by suntong** [comment] 2019-03-04 23:26
Wow, I'm just about to ask, and found it is closed only 20 hours ago. Sweet!

@mholt, where can I try it out? Would you update your https://mholt.github.io/json-to-go/ as well please? 

thx

**Comment by mholt** [comment] 2019-03-05 02:12
@suntong It is updated. Hard-refresh your browser; clear the cache too. Might have to delete the service worker.

**Comment by suntong** [comment] 2019-03-05 05:18
Ah, yeah. got it. thanks. However, there are still duplicated definitions. E.g., 

If you try the example for GitHub, you'll notice that it makes three Owner structs:

```json
type AutoGenerated struct {
	ID               int          `json:"id"`
	Owner            Owner        `json:"owner"`
	Name             string       `json:"name"`
	FullName         string       `json:"full_name"`
	Description      string       `json:"description"`
	Private          bool         `json:"private"`
	Fork             bool         `json:"fork"`
	URL              string       `json:"url"`
	HTMLURL          string       `json:"html_url"`
	CloneURL         string       `json:"clone_url"`
	GitURL           string       `json:"git_url"`
	SSHURL           string       `json:"ssh_url"`
	SvnURL           string       `json:"svn_url"`
	MirrorURL        string       `json:"mirror_url"`
	Homepage         string       `json:"homepage"`
	Language         interface{}  `json:"language"`
	ForksCount       int          `json:"forks_count"`
	StargazersCount  int          `json:"stargazers_count"`
	WatchersCount    int          `json:"watchers_count"`
	Size             int          `json:"size"`
	DefaultBranch    string       `json:"default_branch"`
	OpenIssuesCount  int          `json:"open_issues_count"`
	HasIssues        bool         `json:"has_issues"`
	HasWiki          bool         `json:"has_wiki"`
	HasDownloads     bool         `json:"has_downloads"`
	PushedAt         time.Time    `json:"pushed_at"`
	CreatedAt        time.Time    `json:"created_at"`
	UpdatedAt        time.Time    `json:"updated_at"`
	Permissions      Permissions  `json:"permissions"`
	SubscribersCount int          `json:"subscribers_count"`
	Organization     Organization `json:"organization"`
	Parent           Parent       `json:"parent"`
	Source           Source       `json:"source"`
}

type Owner struct {
	Login             string `json:"login"`
	ID                int    `json:"id"`
	AvatarURL         string `json:"avatar_url"`
	GravatarID        string `json:"gravatar_id"`
	URL               string `json:"url"`
	HTMLURL           string `json:"html_url"`
	FollowersURL      string `json:"followers_url"`
	FollowingURL      string `json:"following_url"`
	GistsURL          string `json:"gists_url"`
	StarredURL        string `json:"starred_url"`
	SubscriptionsURL  string `json:"subscriptions_url"`
	OrganizationsURL  string `json:"organizations_url"`
	ReposURL          string `json:"repos_url"`
	EventsURL         string `json:"events_url"`
	ReceivedEventsURL string `json:"received_events_url"`
	Type              string `json:"type"`
	SiteAdmin         bool   `json:"site_admin"`
}

type Permissions struct {
	Admin bool `json:"admin"`
	Push  bool `json:"push"`
	Pull  bool `json:"pull"`
}

type Organization struct {
	Login             string `json:"login"`
	ID                int    `json:"id"`
	AvatarURL         string `json:"avatar_url"`
	GravatarID        string `json:"gravatar_id"`
	URL               string `json:"url"`
	HTMLURL           string `json:"html_url"`
	FollowersURL      string `json:"followers_url"`
	FollowingURL      string `json:"following_url"`
	GistsURL          string `json:"gists_url"`
	StarredURL        string `json:"starred_url"`
	SubscriptionsURL  string `json:"subscriptions_url"`
	OrganizationsURL  string `json:"organizations_url"`
	ReposURL          string `json:"repos_url"`
	EventsURL         string `json:"events_url"`
	ReceivedEventsURL string `json:"received_events_url"`
	Type              string `json:"type"`
	SiteAdmin         bool   `json:"site_admin"`
}

type Owner struct {
	Login             string `json:"login"`
	ID                int    `json:"id"`
	AvatarURL         string `json:"avatar_url"`
	GravatarID        string `json:"gravatar_id"`
	URL               string `json:"url"`
	HTMLURL           string `json:"html_url"`
	FollowersURL      string `json:"followers_url"`
	FollowingURL      string `json:"following_url"`
	GistsURL          string `json:"gists_url"`
	StarredURL        string `json:"starred_url"`
	SubscriptionsURL  string `json:"subscriptions_url"`
	OrganizationsURL  string `json:"organizations_url"`
	ReposURL          string `json:"repos_url"`
	EventsURL         string `json:"events_url"`
	ReceivedEventsURL string `json:"received_events_url"`
	Type              string `json:"type"`
	SiteAdmin         bool   `json:"site_admin"`
}

type Permissions struct {
	Admin bool `json:"admin"`
	Push  bool `json:"push"`
	Pull  bool `json:"pull"`
}

type Parent struct {
	ID              int         `json:"id"`
	Owner           Owner       `json:"owner"`
	Name            string      `json:"name"`
	FullName        string      `json:"full_name"`
	Description     string      `json:"description"`
	Private         bool        `json:"private"`
	Fork            bool        `json:"fork"`
	URL             string      `json:"url"`
	HTMLURL         string      `json:"html_url"`
	CloneURL        string      `json:"clone_url"`
	GitURL          string      `json:"git_url"`
	SSHURL          string      `json:"ssh_url"`
	SvnURL          string      `json:"svn_url"`
	MirrorURL       string      `json:"mirror_url"`
	Homepage        string      `json:"homepage"`
	Language        interface{} `json:"language"`
	ForksCount      int         `json:"forks_count"`
	StargazersCount int         `json:"stargazers_count"`
	WatchersCount   int         `json:"watchers_count"`
	Size            int         `json:"size"`
	DefaultBranch   string      `json:"default_branch"`
	OpenIssuesCount int         `json:"open_issues_count"`
	HasIssues       bool        `json:"has_issues"`
	HasWiki         bool        `json:"has_wiki"`
	HasDownloads    bool        `json:"has_downloads"`
	PushedAt        time.Time   `json:"pushed_at"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	Permissions     Permissions `json:"permissions"`
}

type Owner struct {
	Login             string `json:"login"`
	ID                int    `json:"id"`
	AvatarURL         string `json:"avatar_url"`
	GravatarID        string `json:"gravatar_id"`
	URL               string `json:"url"`
	HTMLURL           string `json:"html_url"`
	FollowersURL      string `json:"followers_url"`
	FollowingURL      string `json:"following_url"`
	GistsURL          string `json:"gists_url"`
	StarredURL        string `json:"starred_url"`
	SubscriptionsURL  string `json:"subscriptions_url"`
	OrganizationsURL  string `json:"organizations_url"`
	ReposURL          string `json:"repos_url"`
	EventsURL         string `json:"events_url"`
	ReceivedEventsURL string `json:"received_events_url"`
	Type              string `json:"type"`
	SiteAdmin         bool   `json:"site_admin"`
}

type Permissions struct {
	Admin bool `json:"admin"`
	Push  bool `json:"push"`
	Pull  bool `json:"pull"`
}

type Source struct {
	ID              int         `json:"id"`
	Owner           Owner       `json:"owner"`
	Name            string      `json:"name"`
	FullName        string      `json:"full_name"`
	Description     string      `json:"description"`
	Private         bool        `json:"private"`
	Fork            bool        `json:"fork"`
	URL             string      `json:"url"`
	HTMLURL         string      `json:"html_url"`
	CloneURL        string      `json:"clone_url"`
	GitURL          string      `json:"git_url"`
	SSHURL          string      `json:"ssh_url"`
	SvnURL          string      `json:"svn_url"`
	MirrorURL       string      `json:"mirror_url"`
	Homepage        string      `json:"homepage"`
	Language        interface{} `json:"language"`
	ForksCount      int         `json:"forks_count"`
	StargazersCount int         `json:"stargazers_count"`
	WatchersCount   int         `json:"watchers_count"`
	Size            int         `json:"size"`
	DefaultBranch   string      `json:"default_branch"`
	OpenIssuesCount int         `json:"open_issues_count"`
	HasIssues       bool        `json:"has_issues"`
	HasWiki         bool        `json:"has_wiki"`
	HasDownloads    bool        `json:"has_downloads"`
	PushedAt        time.Time   `json:"pushed_at"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	Permissions     Permissions `json:"permissions"`
}
```

**Comment by mholt** [comment] 2019-03-05 06:02
I haven't deployed the latest on master yet, but you're welcome to use it: https://github.com/mholt/json-to-go/pull/49

**Comment by suntong** [comment] 2019-03-05 14:15
Oh, I was hoping that you would update your https://mholt.github.io/json-to-go/ to the latest as well. Do you have recent plan to do that? 

Meanwhile, how can I use #49, or json-to-go? Any document anywhere that I can follow? 

thx

**Comment by mahdi-hosseini** [comment] 2019-03-05 15:32
@suntong 
1. Open your web browser console, preferably Google Chrome.
2. Copy and paste the contents of `json-to-go.js` and hit enter.
3. Replace the test JSON below with yours and once you have done that, hit enter and you should get your Go code.

```javascript
console.log(
    jsonToGo(`
    {
        "test": "a"
    }
    `).go
)
```

**Comment by suntong** [comment] 2019-03-05 15:42
got it, and the duplicated definitions are gone. THX!

**Comment by suntong** [comment] 2019-03-05 22:13
@mholt & @mahdi-hosseini, 

The following json works for previous anonymous struct, but not the current non-anonymous structs. I just get `undefined`. 

Would you double-check please? Thx!

```json
{
  "id": "7a305b33-471c-42cf-9baf-f5220dc17180",
  "version": "1.1",
  "name": "Dummy",
  "url": "",
  "tests": [{
    "id": "3cd0b9fa-aba7-4f9a-b278-c5b43fd9b6be",
    "name": "SeleniumIDE",
    "commands": [{
      "id": "39b58390-385c-4a1e-8915-a993f08cc165",
      "comment": "",
      "command": "open",
      "target": "https://www.seleniumhq.org/",
      "targets": [],
      "value": ""
    }, {
      "id": "6458c851-6c8b-4b82-81d6-66eede61fa2f",
      "comment": "Goto \"Projects\"",
      "command": "echo",
      "target": "",
      "targets": [],
      "value": "Test Step 1"
    }, {
      "id": "bf6c20ea-1a4a-4235-969e-d2b04d193a5b",
      "comment": "",
      "command": "click",
      "target": "linkText=Projects",
      "targets": [
        ["linkText=Projects", "linkText"],
        ["css=a[title=\"Selenium Projects\"]", "css"],
        ["css=#menu_projects > a", "css:finder"],
        ["xpath=//a[contains(text(),'Projects')]", "xpath:link"],
        ["xpath=//li[@id='menu_projects']/a", "xpath:idRelative"],
        ["xpath=//a[contains(@href, '/projects/')]", "xpath:href"],
        ["xpath=//li[5]/a", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "b4e645f8-c16d-45a6-8116-c36b90ad3a68",
      "comment": "Goto \"Selenium IDE\"",
      "command": "echo",
      "target": "",
      "targets": [],
      "value": "Test Step 2"
    }, {
      "id": "ec99567d-e01b-46f8-b773-9a963ef9cc67",
      "comment": "Get into https://www.seleniumhq.org/selenium-ide/",
      "command": "click",
      "target": "linkText=Selenium IDE",
      "targets": [
        ["linkText=Selenium IDE", "linkText"],
        ["css=h3:nth-child(9) > a", "css:finder"],
        ["xpath=//a[contains(text(),'Selenium IDE')]", "xpath:link"],
        ["xpath=//div[@id='mainContent']/div/h3[3]/a", "xpath:idRelative"],
        ["xpath=//a[contains(@href, '/selenium-ide/')]", "xpath:href"],
        ["xpath=//h3[3]/a", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "d5886005-7d6d-4cbf-b400-1feaebb51546",
      "comment": "Goto \"Doc\"",
      "command": "echo",
      "target": "",
      "targets": [],
      "value": "Test Step 3"
    }, {
      "id": "18dc810f-2753-471c-b304-5ded76b99d60",
      "comment": "Get into https://www.seleniumhq.org/selenium-ide/docs/en/introduction/getting-started/",
      "command": "click",
      "target": "linkText=Docs",
      "targets": [
        ["linkText=Docs", "linkText"],
        ["css=li > a", "css"],
        ["css=li:nth-child(1) > a", "css:finder"],
        ["xpath=//a[contains(text(),'Docs')]", "xpath:link"],
        ["xpath=//a[contains(@href, '/selenium-ide/docs/en/introduction/getting-started')]", "xpath:href"],
        ["xpath=//li/a", "xpath:position"]
      ],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "ef0df0fa-eb97-4d88-9e8c-b3aa0be8a687",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["3cd0b9fa-aba7-4f9a-b278-c5b43fd9b6be"]
  }],
  "urls": [],
  "plugins": []
}
```

**Comment by mahdi-hosseini** [comment] 2019-03-05 22:45
@suntong I looked into this and it doesn't seem to be a regression caused by the flatten option that I added. So it looks like you have found a new bug. I presume you need to create a new issue as it's unrelated to flatten logic.

**Comment by suntong** [comment] 2019-03-05 22:50
thanks for checking @mahdi-hosseini , opened in #51.
